#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocalConnect.Android.Resource", IsApplication=true)]

namespace LocalConnect.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::LocalConnect.Android.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::LocalConnect.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int circleCrop = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatio = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000b
			public const int LowContrastFontOnGreenBkg = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int MintCream = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int common_signin_btn_text_dark = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_signin_btn_text_light = 2131034125;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_textfield_activated_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_default_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_full_open_on_phone = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_ic_googleplayservices = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_disabled_focus_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_disabled_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_focus_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_focus_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_normal_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_normal_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_pressed_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_pressed_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_focus_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_disabled_focus_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_disabled_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_focus_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_focus_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_normal_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_normal_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_pressed_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_pressed_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int EditTextGreen = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int EditTextWhite = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int green_textfield_activated_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int green_textfield_default_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int green_textfield_disabled_focused_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int green_textfield_disabled_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int green_textfield_focused_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_plusone_medium_off_client = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_plusone_small_off_client = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_plusone_standard_off_client = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_plusone_tall_off_client = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_view_list_white_36dp = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002f
			public const int ActionsPanel = 2131296303;
			
			// aapt resource value: 0x7f090033
			public const int AddMessageForm = 2131296307;
			
			// aapt resource value: 0x7f090019
			public const int ErrorText = 2131296281;
			
			// aapt resource value: 0x7f09001e
			public const int InitializingPanel = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int LoadingPanel = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int LoginButton = 2131296284;
			
			// aapt resource value: 0x7f090012
			public const int LoginInput = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int LoginPanel = 2131296273;
			
			// aapt resource value: 0x7f09002e
			public const int LongDescription = 2131296302;
			
			// aapt resource value: 0x7f090016
			public const int Mail = 2131296278;
			
			// aapt resource value: 0x7f09001f
			public const int MainLayout = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int MeImage = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int MenuButton = 2131296291;
			
			// aapt resource value: 0x7f090020
			public const int MenuLayout = 2131296288;
			
			// aapt resource value: 0x7f090008
			public const int MessageDateTime = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int MessageRootLayout = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int MessageStatus = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int MessageText = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int MessageTextContainer = 2131296265;
			
			// aapt resource value: 0x7f090032
			public const int MessagesList = 2131296306;
			
			// aapt resource value: 0x7f09002b
			public const int MoreButton = 2131296299;
			
			// aapt resource value: 0x7f090017
			public const int Name = 2131296279;
			
			// aapt resource value: 0x7f090013
			public const int PasswordInput = 2131296275;
			
			// aapt resource value: 0x7f09002a
			public const int PersonImage = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int PersonName = 2131296300;
			
			// aapt resource value: 0x7f090028
			public const int PersonRootView = 2131296296;
			
			// aapt resource value: 0x7f090014
			public const int RegistrationInfoPanel = 2131296276;
			
			// aapt resource value: 0x7f090024
			public const int SearchButton = 2131296292;
			
			// aapt resource value: 0x7f090035
			public const int SendButton = 2131296309;
			
			// aapt resource value: 0x7f09002d
			public const int ShortDescription = 2131296301;
			
			// aapt resource value: 0x7f090018
			public const int Surname = 2131296280;
			
			// aapt resource value: 0x7f090022
			public const int SwitchViewButton = 2131296290;
			
			// aapt resource value: 0x7f090034
			public const int TextInput = 2131296308;
			
			// aapt resource value: 0x7f09001b
			public const int ToogleRegisterButton = 2131296283;
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f090030
			public const int button2 = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int button3 = 2131296305;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f09001a
			public const int linearLayout1 = 2131296282;
			
			// aapt resource value: 0x7f09000f
			public const int listLayout = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int listView = 2131296272;
			
			// aapt resource value: 0x7f090036
			public const int logout = 2131296310;
			
			// aapt resource value: 0x7f090027
			public const int map = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int mapLayout = 2131296294;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f090025
			public const int pager = 2131296293;
			
			// aapt resource value: 0x7f09000e
			public const int personDesc = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int personImage = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int personName = 2131296269;
			
			// aapt resource value: 0x7f090029
			public const int relativeLayout2 = 2131296297;
			
			// aapt resource value: 0x7f090015
			public const int repeatedPassword = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int IncomeMessageItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MapViewFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int OutcomeMessageItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Person = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int SettingsMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppButton = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int AppStyle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
